### PR TITLE
[k256] Make Proj point equality and is_identity faster

### PR DESCRIPTION
**Pull request by LLFourn**
1. `ProjectivePoint::is_identity` was slow because it did an equality check with identity rather than just checking z coordinate == 0
2. Equality check was much slower than necessary because it converted to affine coords first. This algorithm does the check avoiding a modular inversion at the cost of a few multiplications. Around ~70 times faster.

I believe these changes are correct but please review carefully.

### CODE REVIEW

**Comment by LLFourn** [comment]
I added another commit which adds a an fast equality check between projective and affine under the same reasoning.

**Comment by tarcieri** [comment]
Thank you! I'll try to review this soon.

**Comment by tarcieri** [comment]
@fjarri might also be able to provide some input here

**Comment by fjarri** [comment]
Looks good to me, but hopefully someone else can review too. Thanks for looking into this.

**Review by fjarri — APPROVED** [review]

**Pull request merged**
