### PR TITLE
p256: Add implementation of Elligator Squared.

### PR DESCRIPTION
**Pull request by codahale**
This is in big need of more scrutiny, documenting, and refactoring, but I wanted to push early and allow for input.

[Elligator Squared](https://eprint.iacr.org/2014/043.pdf) is obviously not a standard anything, nor is the simplified Shallue-van de Woestijne-Ulas encoding, so I’m pretty open to this being a bad fit for inclusion in this crate. This is well into “science project” territory and really not something I’d responsibly recommend to anyone.

Buuut it’s neat and I’ve got a hobby project which might could use it and it seems like a decent focal point for conversations about what an EC API looks like which would allow me to ~commit these sorts of crimes~ implement this sort of functionality without having to maintain my own fork. At a minimum, that’d probably be access to `FieldElement`, curve constants, and point construction.

Ostensibly this could also be implemented for [k256](https://github.com/sipa/writeups/tree/main/elligator-square-for-bn), but it’d need a similar degree of specialization.

Absolutely no hurry on this, BTW.

### CODE REVIEW

**Comment by tarcieri** [comment]
This looks interesting. I can hopefully review some more this weekend.

**Comment by tarcieri** [comment]
Having recently seen this issue: https://github.com/dalek-cryptography/curve25519-dalek/issues/389

...I'm curious if perhaps we should just have a cargo feature that exposes the `FieldElement` API. It can remain hidden from rustdoc.

There's already an `expose-field` feature in `k256`. We could add a similar one to `p256`, and then it seems like this could be implemented at a library level.

It could potentially even be generic over curves, similar to the SSWU implementation in the `elliptic-curve` crate:

https://docs.rs/elliptic-curve/0.11.12/elliptic_curve/hash2curve/trait.OsswuMap.html

We've been trying to avoid exposing `FieldElement` as doing so is a huge footgun, but I'm seeing enough legitimate use cases it might make sense to reconsider, feature gating it and keeping it hidden but available for the modicum of protocols which do need legitimate access.

Alternatively it could potentially be added to `elliptic-curve` in a similar manner to hash2curve.

cc @str4d

**Comment by codahale** [comment]
> Having recently seen this issue: [dalek-cryptography/curve25519-dalek#389](https://github.com/dalek-cryptography/curve25519-dalek/issues/389)
> 
> ...I'm curious if perhaps we should just have a cargo feature that exposes the `FieldElement` API. It can remain hidden from rustdoc.

I think that’s a good start, but it’s worth noting that this implementation also requires the ability to convert raw coordinates to points and back, plus access to (or duplication of) curve constants.

> We've been trying to avoid exposing `FieldElement` as doing so is a huge footgun, but I'm seeing enough legitimate use cases it might make sense to reconsider, feature gating it and keeping it hidden but available for the modicum of protocols which do need legitimate access.

I feel you on the footgun aspect. The feature could export the hazmat types from a specific hazmat submodule?

> Alternatively a generic implementation of Elligator Squared could potentially be added to `elliptic-curve` in a similar manner to hash2curve.

I was curious if a generic approach would work here, but there’s a few wrinkles to the way the algorithm works which makes me wonder how much structure could be shared for implementations across curves. The sampling algorithm is generic, and embedding a field element in a point is generic w.r.t. curves, but the inverse function is kind of gnarly. I guess if you extracted out the `d` constant (the maximum number of preimages for the inverse embedding) and fixed the potential modulo bias in the sampling algorithm it’d fly.

**Comment by kayabaNerve** [comment]
For my uses, I'd be willing to consent to a lack of semver guarantees and feature flagging, if that provides another developer's perspective. That said, I only need it in dalek for Monero's hash to curve so I don't really count as a user who can give feedback over here :p

**Review by Mitsuecom — APPROVED** [review]

**Review by Mitsuecom — APPROVED** [review]

**Comment by tarcieri** [comment]
@codahale FYI, with the [`primeorder::PrimeCurveParams`](https://docs.rs/primeorder/0.13.6/primeorder/trait.PrimeCurveParams.html) trait you should be able to implement this out-of-tree.

Impl here: https://docs.rs/p256/0.13.2/p256/struct.NistP256.html#impl-PrimeCurveParams-for-NistP256

**Comment by codahale** [comment]
Indeed, I can! https://github.com/codahale/elligator-squared

Mashing field elements into and from bytes isn’t delightful, but it’s functional for now.

Thanks for the update!

**Pull request closed without merging**
