### PR TITLE
p521: projective arithmetic tests

### PR DESCRIPTION
**Pull request by tarcieri**
Uses `impl_projective_arithmetic_tests!` to test projective arithmetic against a set of test vectors.

Includes test vectors from:

http://point-at-infinity.org/ecc/nisttv

### CODE REVIEW

**Comment by MasterAwesome** [comment]
Just noticed the projective tests didn't run as a part of CI, probably due to the wrong feature being used `arithmetic` when only `wip-arithmetic-do-not-use` exists

**Comment by tarcieri** [comment]
Oh wow, you're right: they're not running at all

**Comment by MasterAwesome** [comment]
On the bright side,

```
test affine_to_projective ... ok
test projective_add_and_sub ... ok
test projective_double_and_sub ... ok
test projective_add_vs_double ... ok
test projective_mixed_addition ... ok
test projective_identity_addition ... ok
test test_vector_add_mixed_identity ... ok
test test_vector_double_generator ... ok
test test_vector_repeated_add_mixed ... ok
test test_vector_repeated_add ... ok
test test_vector_scalar_mult ... ok
```
🎉

**Comment by tarcieri** [comment]
Yep, they do pass! See #951

**Pull request merged**
